name: Frist Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: print name
        run: echo "Vel"
      - name: say bye
        run: echo "bye"
    
  
